ecommerce/App_Order/urls.py
from django.urls import path,include

app_name="App_Order"

from App_Order import views

urlpatterns = [
    path("add/<pk>/",views.add_to_cart,name="add")
]

ecommerce/App_Shop/urls.py
from django.urls import path,include

app_name='App_Shop'
from App_Shop import views

urlpatterns = [
    path("",views.Home.as_view(),name="home"),
    path("product_detail/<pk>/",views.Product_Detail.as_view(),name="product_detail"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("App_Shop.urls")),
    path("accounts/",include("App_Account.urls")),
    path("shop/",include("App_Order.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/App_Shop/models.py
from django.db import models



# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.title)
    class Meta :
        verbose_name_plural="Categories"
        
class Product(models.Model):
    mainimage=models.ImageField(upload_to="products/",blank=True)
    name=models.CharField( max_length=250) 
    category=models.ForeignKey(Category, on_delete=models.CASCADE,related_name="category")
    preview_text=models.TextField(max_length="140",verbose_name="preview_text")
    detail_text=models.TextField(max_length="1000",verbose_name="detail_text")
    price=models.FloatField()
    old_price=models.FloatField(default=0.00)
    created=models.DateTimeField( auto_now_add=True)
    
    
    def __str__(self):
        return str(self.name)
    
    class Meta:
        ordering=['-created',]

ecommerce/App_Shop/views.py
from django.shortcuts import render


from .models import Category,Product


#authentication Mixin 
from django.contrib.auth.mixins import LoginRequiredMixin
#import views 
from django.views.generic import ListView,DetailView

# Create your views here.
class Home(ListView):
    model=Product
    template_name="App_Shop/home.html"
    

class Product_Detail(LoginRequiredMixin,DetailView):
    model=Product
    template_name="App_Shop/product_detail.html"

ecommerce/templates/App_Shop/all_products.html
<div>
  {% block content %}

  <div>
    <div>
      <div class="max-w-screen-xl mx-auto p-5 sm:p-10 md:p-16">
        <div class="border-b mb-5 flex justify-between text-sm">
          <div
            class="text-indigo-600 flex items-center pb-2 pr-2 border-b-2 border-indigo-600 uppercase"
          >
            <svg
              class="h-6 mr-3"
              version="1.1"
              id="Capa_1"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              x="0px"
              y="0px"
              viewBox="0 0 455.005 455.005"
              style="enable-background: new 0 0 455.005 455.005"
              xml:space="preserve"
            >
              <g>
                <path
                  d="M446.158,267.615c-5.622-3.103-12.756-2.421-19.574,1.871l-125.947,79.309c-3.505,2.208-4.557,6.838-2.35,10.343 c2.208,3.505,6.838,4.557,10.343,2.35l125.947-79.309c2.66-1.675,4.116-1.552,4.331-1.432c0.218,0.12,1.096,1.285,1.096,4.428 c0,8.449-6.271,19.809-13.42,24.311l-122.099,76.885c-6.492,4.088-12.427,5.212-16.284,3.084c-3.856-2.129-6.067-7.75-6.067-15.423 c0-19.438,13.896-44.61,30.345-54.967l139.023-87.542c2.181-1.373,3.503-3.77,3.503-6.347s-1.323-4.974-3.503-6.347L184.368,50.615 c-2.442-1.538-5.551-1.538-7.993,0L35.66,139.223C15.664,151.815,0,180.188,0,203.818v4c0,23.63,15.664,52.004,35.66,64.595 l209.292,131.791c3.505,2.207,8.136,1.154,10.343-2.35c2.207-3.505,1.155-8.136-2.35-10.343L43.653,259.72 C28.121,249.941,15,226.172,15,207.818v-4c0-18.354,13.121-42.122,28.653-51.902l136.718-86.091l253.059,159.35l-128.944,81.196 c-20.945,13.189-37.352,42.909-37.352,67.661c0,13.495,4.907,23.636,13.818,28.555c3.579,1.976,7.526,2.956,11.709,2.956 c6.231,0,12.985-2.176,19.817-6.479l122.099-76.885c11.455-7.213,20.427-23.467,20.427-37.004 C455.004,277.119,451.78,270.719,446.158,267.615z"
                ></path>
                <path
                  d="M353.664,232.676c2.492,0,4.928-1.241,6.354-3.504c2.207-3.505,1.155-8.136-2.35-10.343l-173.3-109.126 c-3.506-2.207-8.136-1.154-10.343,2.35c-2.207,3.505-1.155,8.136,2.35,10.343l173.3,109.126 C350.916,232.303,352.298,232.676,353.664,232.676z"
                ></path>
                <path
                  d="M323.68,252.58c2.497,0,4.938-1.246,6.361-3.517c2.201-3.509,1.14-8.138-2.37-10.338L254.46,192.82 c-3.511-2.202-8.139-1.139-10.338,2.37c-2.201,3.51-1.14,8.138,2.37,10.338l73.211,45.905 C320.941,252.21,322.318,252.58,323.68,252.58z"
                ></path>
                <path
                  d="M223.903,212.559c-3.513-2.194-8.14-1.124-10.334,2.39c-2.194,3.514-1.124,8.14,2.39,10.334l73.773,46.062 c1.236,0.771,2.608,1.139,3.965,1.139c2.501,0,4.947-1.251,6.369-3.529c2.194-3.514,1.124-8.14-2.39-10.334L223.903,212.559z"
                ></path>
                <path
                  d="M145.209,129.33l-62.33,39.254c-2.187,1.377-3.511,3.783-3.503,6.368s1.345,4.983,3.54,6.348l74.335,46.219 c1.213,0.754,2.586,1.131,3.96,1.131c1.417,0,2.833-0.401,4.071-1.201l16.556-10.7c3.479-2.249,4.476-6.891,2.228-10.37 c-2.248-3.479-6.891-4.475-10.37-2.228l-12.562,8.119l-60.119-37.38l48.2-30.355l59.244,37.147l-6.907,4.464 c-3.479,2.249-4.476,6.891-2.228,10.37c2.249,3.479,6.894,4.476,10.37,2.228l16.8-10.859c2.153-1.392,3.446-3.787,3.429-6.351 c-0.018-2.563-1.344-4.94-3.516-6.302l-73.218-45.909C150.749,127.792,147.647,127.795,145.209,129.33z"
                ></path>
                <path
                  d="M270.089,288.846c2.187-3.518,1.109-8.142-2.409-10.329l-74.337-46.221c-3.518-2.188-8.143-1.109-10.329,2.409 c-2.187,3.518-1.109,8.142,2.409,10.329l74.337,46.221c1.232,0.767,2.601,1.132,3.953,1.132 C266.219,292.387,268.669,291.131,270.089,288.846z"
                ></path>
                <path
                  d="M53.527,192.864c-2.187,3.518-1.109,8.142,2.409,10.329l183.478,114.081c1.232,0.767,2.601,1.132,3.953,1.132 c2.506,0,4.956-1.256,6.376-3.541c2.187-3.518,1.109-8.142-2.409-10.329L63.856,190.455 C60.338,188.266,55.714,189.346,53.527,192.864z"
                ></path>
              </g>
            </svg>
            <a href="#" class="font-semibold inline-block">Products</a>
          </div>
          <a href="#">See All</a>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-10">
          <!-- CARD 1 -->

          {% for product in object_list %}
          <div class="rounded overflow-hidden shadow-lg flex flex-col">
            <a href=""></a>
            <div class="relative">
              <a href="{% url "App_Shop:product_detail" pk=product.pk %}">
                <img class="w-full" src="{{product.mainimage.url}}" alt="" />
                <div
                  class="hover:bg-transparent transition duration-300 absolute bottom-0 top-0 right-0 left-0 bg-gray-900 opacity-25"
                ></div>
              </a>
              <a href="#!">
                <div
                  class="text-xs absolute top-0 right-0 bg-indigo-600 px-4 py-2 text-white mt-3 mr-3 hover:bg-white hover:text-indigo-600 transition duration-500 ease-in-out"
                >
                  {{product.category}}
                </div>
              </a>
            </div>
            <div class="px-6 py-4 mb-auto">
              <a
                href="{% url "App_Shop:product_detail" pk=product.pk %}"
                class="font-medium text-lg inline-block hover:text-indigo-600 transition duration-500 ease-in-out inline-block mb-2"
                >{{product.name}}</a
              >
              <p
                class="font-medium text-lg inline-block hover:text-indigo-600 transition duration-500 ease-in-out inline-block mb-2"
              >
                $ {{product.price}}
              </p>
              <p>Old Price :{{product.old_price}}</p>

              <p class="text-gray-500 text-sm">{{product.preview_text}}</p>
            </div>
            <div
              class="px-6 py-3 flex flex-row items-center justify-between bg-gray-100"
            >
              <span
                href="#"
                class="py-1 text-xs font-regular text-gray-900 mr-1 flex flex-row items-center"
              >
                <svg
                  height="13px"
                  width="13px"
                  version="1.1"
                  id="Layer_1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  x="0px"
                  y="0px"
                  viewBox="0 0 512 512"
                  style="enable-background: new 0 0 512 512"
                  xml:space="preserve"
                >
                  <g>
                    <g>
                      <path
                        d="M256,0C114.837,0,0,114.837,0,256s114.837,256,256,256s256-114.837,256-256S397.163,0,256,0z M277.333,256 c0,11.797-9.536,21.333-21.333,21.333h-85.333c-11.797,0-21.333-9.536-21.333-21.333s9.536-21.333,21.333-21.333h64v-128 c0-11.797,9.536-21.333,21.333-21.333s21.333,9.536,21.333,21.333V256z"
                      ></path>
                    </g>
                  </g>
                </svg>
                <span class="ml-1">{{product.created}} Created mins ago</span>
              </span>
            </div>
          </div>

          {% endfor %}
        </div>
      </div>
    </div>

    {% endblock content %}
  </div>
</div>

ecommerce/templates/App_Shop/home.html
{% extends "base.html" %}
<div>{% block title %}Django | E-com{% endblock title %}</div>
<div>{% load tailwind_filters %} {% load crispy_forms_tags %}</div>
<div>
  {% block content %}

  <div>
    <header>
      <!-- Hero Container -->
      <div class="mx-auto w-full px-5 py-16 md:px-10 md:py-20 bg-gray-200">
        <!-- Component -->
        <div
          class="grid items-center justify-items-start gap-8 sm:gap-20 lg:grid-cols-2"
        >
          <!-- Hero Content -->
          <div class="flex flex-col">
            <!-- Hero Title -->
            <h1 class="mb-4 text-4xl font-bold md:text-6xl">
              An Unobtrusive Innovatiive With A True Beauty !
            </h1>
            <p
              class="mb-6 max-w-lg text-sm text-gray-500 sm:text-xl md:mb-10 lg:mb-12"
            >
              Our products use finest materials and stunning design to create
              something special, bold textiles and unique prints, with high our
              quality craftsmanship design.
            </p>
            <!-- Hero Button -->
            <a
              href="#"
              class="mb-6 mr-6 w-36 rounded-md bg-black px-6 py-3 text-center font-semibold text-white md:mb-10 lg:mb-12 lg:mr-8"
            >
              Get Started
            </a>
            <!-- Hero Comment -->
            <div class="max-w-xs">
              <p class="mb-4 text-sm text-gray-500">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
                aliquam, purus
              </p>
              <div class="flex items-center gap-11 sm:flex-row">
                <div class="flex items-center">
                  <img
                    src="https://vouge.wpengine.com/rtl-demo/wp-content/uploads/sites/3/2024/07/shop-8-01.jpg"
                    alt=""
                    class="mr-2 inline-block rounded-full object-cover h-7 w-7 sm:h-7"
                  />
                  <p class="text-sm font-bold">Aleeyah</p>
                </div>
                <div class="flex items-center">
                  <p class="mr-2 text-sm font-bold">5.0</p>
                  <img
                    src="https://assets.website-files.com/6357722e2a5f19121d37f84d/6357722e2a5f195bcf37f880_Vector.svg"
                    alt=""
                    class="mr-1.5 inline-block w-4"
                  />
                  <img
                    src="https://assets.website-files.com/6357722e2a5f19121d37f84d/6357722e2a5f195bcf37f880_Vector.svg"
                    alt=""
                    class="mr-1.5 inline-block w-4"
                  />
                  <img
                    src="https://assets.website-files.com/6357722e2a5f19121d37f84d/6357722e2a5f195bcf37f880_Vector.svg"
                    alt=""
                    class="mr-1.5 inline-block w-4"
                  />
                  <img
                    src="https://assets.website-files.com/6357722e2a5f19121d37f84d/6357722e2a5f195bcf37f880_Vector.svg"
                    alt=""
                    class="mr-1.5 inline-block w-4"
                  />
                  <img
                    src="https://assets.website-files.com/6357722e2a5f19121d37f84d/6357722e2a5f195bcf37f880_Vector.svg"
                    alt=""
                    class="mr-1.5 inline-block w-4"
                  />
                </div>
              </div>
            </div>
          </div>
          <!-- Hero Image -->

          <img
            src="https://vouge.wpengine.com/rtl-demo/wp-content/uploads/sites/3/2024/07/shop-8-01.jpg"
            alt=""
            class="inline-block h-full w-full max-w-2xl rounded"
          />
        </div>
      </div>
    </header>
  </div>
<div>
  {% include "App_Shop/all_products.html" %}
</div>
  
  </div>

  {% endblock content %}
</div>

ecommerce/templates/App_Shop/product_detail.html
{% extends "base.html" %}
<div>{% block title %}product_detils{% endblock title %}</div>

<div>
  {% block content %}

  <div>
    <div class="mt-10">
      <div
        class="p-2 grid gap-3 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2"
      >
        <div>
          <img
            src="{{object.mainimage.url}}"
            alt="Product-image"
            class="w-full rounded-lg shadow-md mb-4"
            style="height: 500px"
            id=""
          />
        </div>
        <div>
          <div class="w-full md:w-1/2 px-4">
            <h2 class="text-3xl font-bold mb-2">{{object.name}}</h2>
            <p class="text-gray-600 mb-4">sku: {{object.id}}</p>

            <div class="mb-4">
              <span class="text-2xl font-bold mr-2">{{object.price}}</span>
              <span class="text-gray-500 line-through"
                >{{object.old_price}}</span
              >
            </div>
            <p class="text-gray-700 mb-6">{{object.preview_text}}</p>

            <div class="mb-6">
              <label
                for="quantity"
                class="block text-sm font-medium text-gray-700 mb-1"
                >Quantity:</label
              >
              <input
                type="number"
                id="quantity"
                name="quantity"
                min="1"
                value="1"
                class="w-12 text-center rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              />
            </div>

            <div class="flex space-x-4 mb-6">
              <a href="{% url "App_Order:add" pk=object.pk %}">
                <button
                  class="bg-indigo-600 flex gap-2 items-center text-white px-6 py-2 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="size-6"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
                    />
                  </svg>
                  Add to Cart
                </button>
              </a>

              <a href="">
                <button
                  class="bg-gray-200 flex gap-2 items-center text-gray-800 px-6 py-2 rounded-md hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="size-6"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"
                    />
                  </svg>
                  Wishlist
                </button>
              </a>
            </div>

            <div class="mb-5">
              <h3 class="text-lg font-semibold mb-2">Key Features:</h3>
              <div class="p-2 shadow-md rounded">
                <p class="capitalize">{{object.detail_text}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}
</div>