ecommerce/App_Account/urls.py
from django.urls import path

app_name='App_Account'

from App_Account import views

urlpatterns = [
    path("signup/",views.signup,name='signup'),
    path("login/",views.userlogin,name='login'),
    path("logout/",views.user_logout,name="logout"),
    path("profile",views.user_profile,name="profile")
]

ecommerce/App_Shop/urls.py
from django.urls import path,include

app_name='App_Shop'
from App_Shop import views

urlpatterns = [
    path("",views.Home.as_view(),name="home"),
    path("product_detail/<pk>/",views.Product_Detail.as_view(),name="product_detail"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("App_Shop.urls")),
    path("accounts/",include("App_Account.urls")),
    path("shop/",include("App_Order.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}django-ecommerce{% endblock title %}</title>
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>
  <body>
    <div>{% include "navbar.html" %}</div>
    <div>{% block content %} {% endblock content %}</div>
    <div>{% include "footer.html" %}</div>

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>
  </body>
</html>

ecommerce/templates/navbar.html
{% block content %}

<nav class="sticky top-0 z-10 bg-white text-black">
  <div
    class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"
  >
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span
        class="self-center text-2xl font-semibold whitespace-nowrap uppercase"
      >
        Django | E-com
      </span>
    </a>
    <button
      data-collapse-toggle="navbar-default"
      type="button"
      class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
      aria-controls="navbar-default"
      aria-expanded="false"
    >
      <span class="sr-only">Open main menu</span>
      <svg
        class="w-5 h-5"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 17 14"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M1 1h15M1 7h15M1 13h15"
        />
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul
        class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white"
      >
      {% if request.user.is_authenticated %}
      <li>
          <a
            href="{% url "App_Shop:home" %}"
            class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0"
            aria-current="page"
            >Home</a
          >
        </li>
        <li>
          <a
            href="{% url "App_Account:profile" %}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500"
            >Cart
          </a>
        </li>
        <li>
          <a
            href="{% url "App_Account:profile" %}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500"
            >Orders
          </a>
        </li>
        <li>
          <a
            href="{% url "App_Account:profile" %}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500"
            >Profile
          </a>
        </li>
        <li>
          <a
            href="{% url "App_Account:logout" %}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700"
            >Logout</a
          >
        </li>
      {% else %}
        <li>
          <a
            href=""
            class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0"
            aria-current="page"
            >Home</a
          >
        </li>
      <li>
          <a
            href="{% url "App_Account:signup" %}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700"
            >SignUp</a
          >
        </li>
        <li>
          <a
            href="{% url "App_Account:login" %}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700"
            >Login</a
          >
        </li>
      {% endif %}
        

        
        
        
      </ul>
    </div>
  </div>
</nav>
{% endblock content %}